export const FETCH_TICKETS_BEGIN = 'FETCH_TICKETS_BEGIN';
export const FETCH_TICKTES_SUCCESS = 'FETCH_TICKETS_SUCCESS';
export const FETCH_TICKTES_FAILURE = 'FETCH_TICKETS_FAILURE';

export const UPDATE_TICKETS = 'TICKETS_UPDATE';