export const USER_AUTHORIZE = 'USER_AUTHORIZE';
export const USER_AUTHORIZED = 'USER_AUTHORIZED';
export const USER_UNAUTHORIZE = 'USER_UNAUTHORIZE';
export const USER_UNAUTHORIZED = 'USER_UNAUTHORIZED';